[package]
name = "orga"
version = "0.1.10"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
description = "State machine engine"
license = "MIT"

[dependencies]
failure = "0.1.8"
abci2 = { git = "https://github.com/nomic-io/abci2", rev = "e452e6ec1d672c415a93e154921f2a2a952b53dc", optional = true }
merk = { git = "https://github.com/nomic-io/merk", rev = "e5a0baed8086fedc4fa5b99c5fc969697d0e498b", optional = true }
tendermint-rpc = { version = "0.19.0", features = ["http-client"], optional = true }
tendermint = { version = "0.19.0", optional = true }
tendermint-proto = { version = "0.19.0", optional = true }
orga-macros = { path = "macros", version = "0.1.0" }
seq-macro = "0.1.4"
log = "0.4.8"
blocking = "0.4.7"
ed = "0.1.3"

[package.metadata.docs.rs]
features = ["abci", "merk"]

[features]
abci = ["abci2", "tendermint", "tendermint-rpc"]

[profile.release]
lto = true
